version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build

jobs:
  build:
    docker:
      - image: "cimg/ruby:3.1"
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker:
      - image: "cimg/ruby:3.1"
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: "cimg/ruby:3.1"
      # - environment:
      #     POSTGRES_DB: service_objects_rails_test
      #     POSTGRES_PASSWORD: ""
      #     POSTGRES_USER: circleci-db-user
      #   image: "circleci/postgres:9.5-alpine"
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      # PGHOST: 127.0.0.1
      # PGPASSWORD: ""
      # PGUSER: circleci-db-user
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
