version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  codecov: codecov/codecov@3.2.2

workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build

jobs:
  build:
    docker:
      - image: "cimg/ruby:3.1"
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker:
      - image: "cimg/ruby:3.1"
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: "cimg/ruby:3.1"
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
